### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by matthiasfostel** [CM12-1-Douglas/android_device_amazon_douglas#2]
I just wanted to thank you for the work you put into pulling together this build.

You've made several people very happy by helping them escape Amazon's horrible Android design.

**Comment by R0rt1z2** [comment]
> I just wanted to thank you for the work you put into pulling together this build.
> 
> You've made several people very happy by helping them escape Amazon's horrible Android design.

Thanks, glad that you like the ROM.
Cheers!
